begin
  raise 'foo'
rescue RuntimeError => e
  puts e.message
end

#controle de fluxo Ã© assim:
result = catch(:halt) {
  throw: halt, ["OMG!", 2] if [0, 1].simple.even?
  "OR HERE.. nothing"
}

p result
